# script for investigating met office AWS data

- data from https://registry.opendata.aws/met-office-uk-land-observations/
- last 7 days (168 hrs) of data
- frequency: minutely

In [1]:
import boto3
import pandas as pd
from io import BytesIO
from botocore import UNSIGNED
from botocore.config import Config

In [2]:
import boto3 # may need to set up aws credentials?
from botocore import UNSIGNED
from botocore.config import Config


BUCKET_NAME = "met-office-land-observations-data"
# ^ most important bit is the bucket name, which is public and can be found in the met office docs

s3 = boto3.client(
    "s3",
    region_name="eu-west-2",
    config=Config(signature_version=UNSIGNED), # no authentication, public. otherwise boto3 expects aws creds
)

response = s3.list_objects_v2(
    Bucket=BUCKET_NAME,
    MaxKeys=10, # only show 10 items for now
)

for item in response.get("Contents", []):
    print(item["Key"])

202609161059_202609160906_202609160959/high_beach_automatic_weather_station_4291e137-ae60-42a9-9258-182cf338f7b0.csv
202609161159_202609161000_202609161059/high_beach_automatic_weather_station_c1ee576f-4222-4761-8675-95c2c7fc0080.csv
202609161259_202609161100_202609161159/high_beach_automatic_weather_station_8b3ab5de-09f1-4d75-90b2-a951f059114e.csv
202609161359_202609161200_202609161259/high_beach_automatic_weather_station_762c7486-0600-4095-aa6b-8ecd038f6d7d.csv
202609161459_202609161300_202609161359/high_beach_automatic_weather_station_b5b40431-ff40-45cf-8b3f-5e4762898436.csv
202609161559_202609161400_202609161459/high_beach_automatic_weather_station_b1fa2e0e-d3fd-4b3f-957a-3476284880b1.csv
202609161659_202609161500_202609161559/high_beach_automatic_weather_station_9d388201-fa26-4321-9557-61484bd58b35.csv
202609161759_202609161600_202609161659/high_beach_automatic_weather_station_952763c0-2285-4e02-9864-63bf4a53dce6.csv
202609161859_202609161700_202609161759/high_beach_automatic_weather_station_5ce3710f-d029-469c-8af1-e67782e102ca.csv
202609161959_202609161800_202609161859/high_beach_automatic_weather_station_b58ce650-7458-491d-9636-108a9c7e575c.csv

In [3]:
first_key = response["Contents"][0]["Key"]

print(first_key)

202609161059_202609160906_202609160959/high_beach_automatic_weather_station_4291e137-ae60-42a9-9258-182cf338f7b0.csv

In [4]:
response

{'ResponseMetadata': {'RequestId': 'KCK422XP7CM8MGJP',
  'HostId': 'uqaNzzvRq81F1iLpl6enlqc4E05iOPA1dRJP+lyFROmzsmVW4HDMdSAAZiO7vAoBHK1UhRMq4Ma/MbKfAxAtHoDbO+UqE1S5',
  'HTTPStatusCode': 200,
  'HTTPHeaders': {'x-amz-id-2': 'uqaNzzvRq81F1iLpl6enlqc4E05iOPA1dRJP+lyFROmzsmVW4HDMdSAAZiO7vAoBHK1UhRMq4Ma/MbKfAxAtHoDbO+UqE1S5',
   'x-amz-request-id': 'KCK422XP7CM8MGJP',
   'server': 'AmazonS3',
   'date': 'Tue, 29 Sep 2026 10:52:39 GMT',
   'x-amz-bucket-region': 'eu-west-2',
   'content-type': 'application/xml',
   'transfer-encoding': 'chunked'},
  'RetryAttempts': 0},
 'IsTruncated': True,
 'Contents': [{'Key': '202609161059_202609160906_202609160959/high_beach_automatic_weather_station_4291e137-ae60-42a9-9258-182cf338f7b0.csv',
   'LastModified': datetime.datetime(2026, 9, 22, 11, 16, 38, tzinfo=tzutc()),
   'ETag': '"d1962e1c4f8f6376e6e1bdbd63d54288"',
   'ChecksumAlgorithm': ['CRC32'],
   'ChecksumType': 'FULL_OBJECT',
   'Size': 31302,
   'StorageClass': 'STANDARD'},
  {'Key': '202609161159_202609161000_202609161059/high_beach_automatic_weather_station_c1ee576f-4222-4761-8675-95c2c7fc0080.csv',
   'LastModified': datetime.datetime(2026, 9, 22, 0, 2, 14, tzinfo=tzutc()),
   'ETag': '"389baf0a282a397099b3a7a7f1c35e4a"',
   'ChecksumAlgorithm': ['CRC32'],
   'ChecksumType': 'FULL_OBJECT',
   'Size': 32144,
   'StorageClass': 'STANDARD'},
  {'Key': '202609161259_202609161100_202609161159/high_beach_automatic_weather_station_8b3ab5de-09f1-4d75-90b2-a951f059114e.csv',
   'LastModified': datetime.datetime(2026, 9, 22, 1, 16, 10, tzinfo=tzutc()),
   'ETag': '"ec7281182d50292a5a55e18c87da6de8"',
   'ChecksumAlgorithm': ['CRC32'],
   'ChecksumType': 'FULL_OBJECT',
   'Size': 30204,
   'StorageClass': 'STANDARD'},
  {'Key': '202609161359_202609161200_202609161259/high_beach_automatic_weather_station_762c7486-0600-4095-aa6b-8ecd038f6d7d.csv',
   'LastModified': datetime.datetime(2026, 9, 22, 2, 5, 50, tzinfo=tzutc()),
   'ETag': '"829727a5c436f296cd3c484dc21b0f44"',
   'ChecksumAlgorithm': ['CRC32'],
   'ChecksumType': 'FULL_OBJECT',
   'Size': 21640,
   'StorageClass': 'STANDARD'},
  {'Key': '202609161459_202609161300_202609161359/high_beach_automatic_weather_station_b5b40431-ff40-45cf-8b3f-5e4762898436.csv',
   'LastModified': datetime.datetime(2026, 9, 22, 3, 21, 23, tzinfo=tzutc()),
   'ETag': '"2ed85b2bd418983b4f87564ec6db21b5"',
   'ChecksumAlgorithm': ['CRC32'],
   'ChecksumType': 'FULL_OBJECT',
   'Size': 20646,
   'StorageClass': 'STANDARD'},
  {'Key': '202609161559_202609161400_202609161459/high_beach_automatic_weather_station_b1fa2e0e-d3fd-4b3f-957a-3476284880b1.csv',
   'LastModified': datetime.datetime(2026, 9, 22, 4, 10, 45, tzinfo=tzutc()),
   'ETag': '"371628b983e6cff63f74c81944e494f7"',
   'ChecksumAlgorithm': ['CRC32'],
   'ChecksumType': 'FULL_OBJECT',
   'Size': 20151,
   'StorageClass': 'STANDARD'},
  {'Key': '202609161659_202609161500_202609161559/high_beach_automatic_weather_station_9d388201-fa26-4321-9557-61484bd58b35.csv',
   'LastModified': datetime.datetime(2026, 9, 22, 5, 1, 29, tzinfo=tzutc()),
   'ETag': '"0a6857c4a2c7125a16184ec6851c052f"',
   'ChecksumAlgorithm': ['CRC32'],
   'ChecksumType': 'FULL_OBJECT',
   'Size': 21630,
   'StorageClass': 'STANDARD'},
  {'Key': '202609161759_202609161600_202609161659/high_beach_automatic_weather_station_952763c0-2285-4e02-9864-63bf4a53dce6.csv',
   'LastModified': datetime.datetime(2026, 9, 22, 6, 16, 21, tzinfo=tzutc()),
   'ETag': '"c5a81dcbc6ecfbc1dc02777e589451ff"',
   'ChecksumAlgorithm': ['CRC32'],
   'ChecksumType': 'FULL_OBJECT',
   'Size': 26390,
   'StorageClass': 'STANDARD'},
  {'Key': '202609161859_202609161700_202609161759/high_beach_automatic_weather_station_5ce3710f-d029-469c-8af1-e67782e102ca.csv',
   'LastModified': datetime.datetime(2026, 9, 22, 7, 6, 32, tzinfo=tzutc()),
   'ETag': '"14092414d68e799bd6de43f7307fd065"',
   'ChecksumAlgorithm': ['CRC32'],
   'ChecksumType': 'FULL_OBJECT',
   'Size': 30905,
   'StorageClass': 'STANDARD'},
  {'Key': '202609161959_202609161800_202609161859/high_beach_automatic_weather_station_b58ce650-7458-491d-9636-108a9c7e575c.csv',
   'LastModified': datetime.datetime(2026, 9, 22, 8, 21, 42, tzinfo=tzutc()),
   'ETag': '"684f7a40669bf987c587c442f582c5c0"',
   'ChecksumAlgorithm': ['CRC32'],
   'ChecksumType': 'FULL_OBJECT',
   'Size': 32204,
   'StorageClass': 'STANDARD'}],
 'Name': 'met-office-land-observations-data',
 'Prefix': '',
 'MaxKeys': 10,
 'EncodingType': 'url',
 'KeyCount': 10,
 'NextContinuationToken': '1cMqOGsZf9M6pMXn0x0WqCPXrY+wXsfRqG1wfRIYjUNPIzsCRZgIesW8H8NaGyD9P47rXXerkQ6WeV5gygZD6XILHGXa48j+PAVnb8PoBBDfbUGotFLrA4kJKGFNZLQgzCXc/VYvYOp7xle7mDEgeJWxqEC4CrxZxM/Xps/IZobzBjDSOEsGUipJdLngTcm9UiIXW7IEbdrEXpjJhG7LBqA=='}

In [5]:
csv_response = s3.get_object(
    Bucket=BUCKET_NAME,
    Key=first_key,
)

In [6]:
csv_response.keys()

dict_keys(['ResponseMetadata', 'AcceptRanges', 'Expiration', 'LastModified', 'ContentLength', 'ETag', 'ChecksumCRC32', 'ChecksumType', 'VersionId', 'ContentType', 'ServerSideEncryption', 'Metadata', 'ReplicationStatus', 'Body'])

In [7]:
raw_data = csv_response["Body"].read()

print(raw_data[:2000].decode("utf-8"))

timestep|name|longitude|latitude|accumulated_precipitation_1_minute_total|accumulated_precipitation_1_minute_total_qc|air_pressure_near_surface_1_minute_mean|air_pressure_near_surface_1_minute_mean_qc|air_pressure_near_surface_mean_sea_level_1_minute_mean|air_pressure_near_surface_mean_sea_level_1_minute_mean_qc|air_temperature_near_surface_1_minute_mean|air_temperature_near_surface_1_minute_mean_qc|air_temperature_near_surface_secondary_1_minute_mean|air_temperature_near_surface_secondary_1_minute_mean_qc|air_temperature_near_surface_sensor2_1_minute_mean|air_temperature_near_surface_sensor2_1_minute_mean_qc|cloud_base_height_layer1_1_minute_30_minute_rolling_min|cloud_base_height_layer1_1_minute_30_minute_rolling_min_qc|cloud_base_height_layer2_1_minute_30_minute_rolling_min|cloud_base_height_layer2_1_minute_30_minute_rolling_min_qc|cloud_base_height_layer3_1_minute_30_minute_rolling_min|cloud_base_height_layer3_1_minute_30_minute_rolling_min_qc|cloud_cover_layer1_1_minute_30_minute_weighted_mean|cloud_cover_layer1_1_minute_30_minute_weighted_mean_qc|cloud_cover_layer2_1_minute_30_minute_weighted_mean|cloud_cover_layer2_1_minute_30_minute_weighted_mean_qc|cloud_cover_layer3_1_minute_30_minute_weighted_mean|cloud_cover_layer3_1_minute_30_minute_weighted_mean_qc|cloud_cover_total_1_minute_30_minute_weighted_mean|cloud_cover_total_1_minute_30_minute_weighted_mean_qc|dew_point_temperature_1_minute_mean|dew_point_temperature_1_minute_mean_qc|direct_solar_irradiance_1_minute_60_minute_total|direct_solar_irradiance_1_minute_60_minute_total_qc|direct_solar_irradiance_1_minute_binary|direct_solar_irradiance_1_minute_binary_qc|direct_solar_irradiance_1_minute_mean|direct_solar_irradiance_1_minute_mean_qc|direct_solar_irradiance_secondary_1_minute_mean|direct_solar_irradiance_secondary_1_minute_mean_qc|global_radiation_1_minute_mean|global_radiation_1_minute_mean_qc|land_surface_temperature_concrete_1_minute_mean|land_surface_temperature_concrete_1_minute_mean_qc|land_surfac

In [8]:
import pandas as pd
from io import BytesIO

# df = pd.read_csv(BytesIO(raw_data))

# this code fails because of the vertical bar delimiter

Vertical bar is delimiter, while pd.read.csv assumes commas by default. So, fix this

In [9]:
df = pd.read_csv(BytesIO(raw_data), sep="|")

In [10]:
df.head()

,timestep,name,longitude,latitude,accumulated_precipitation_1_minute_total,accumulated_precipitation_1_minute_total_qc,air_pressure_near_surface_1_minute_mean,air_pressure_near_surface_1_minute_mean_qc,air_pressure_near_surface_mean_sea_level_1_minute_mean,air_pressure_near_surface_mean_sea_level_1_minute_mean_qc,...,soil_temperature_100cm_1_minute_mean,soil_temperature_100cm_1_minute_mean_qc,soil_temperature_10cm_1_minute_mean,soil_temperature_10cm_1_minute_mean_qc,soil_temperature_30cm_1_minute_mean,soil_temperature_30cm_1_minute_mean_qc,wind_direction_near_surface_1_minute_mean,wind_direction_near_surface_1_minute_mean_qc,wind_speed_near_surface_1_minute_mean,wind_speed_near_surface_1_minute_mean_qc
0,2026-09-16T09:06:00Z,High Beach Automatic Weather Station,0.04,51.66,NaN,NaN,NaN,NaN,NaN,NaN,...,18.484945,"{""good"": []}",15.791245,"{""good"": []}",18.254480,"{""good"": []}",NaN,NaN,NaN,NaN
1,2026-09-16T09:07:00Z,High Beach Automatic Weather Station,0.04,51.66,NaN,NaN,NaN,NaN,NaN,NaN,...,18.484918,"{""good"": []}",15.807900,"{""good"": []}",18.253000,"{""good"": []}",NaN,NaN,NaN,NaN
2,2026-09-16T09:08:00Z,High Beach Automatic Weather Station,0.04,51.66,NaN,NaN,NaN,NaN,NaN,NaN,...,18.485030,"{""suspect"": [""2 case(s) of \""missing previous ...",15.824680,"{""suspect"": [""2 case(s) of \""missing previous ...",18.250923,"{""suspect"": [""2 case(s) of \""missing previous ...",NaN,NaN,NaN,NaN
3,2026-09-16T09:09:00Z,High Beach Automatic Weather Station,0.04,51.66,NaN,NaN,NaN,NaN,NaN,NaN,...,18.484772,"{""good"": []}",15.841033,"{""good"": []}",18.249527,"{""good"": []}",NaN,NaN,NaN,NaN
4,2026-09-16T09:10:00Z,High Beach Automatic Weather Station,0.04,51.66,NaN,NaN,NaN,NaN,NaN,NaN,...,18.484910,"{""suspect"": [""2 case(s) of \""missing previous ...",15.857415,"{""suspect"": [""2 case(s) of \""missing previous ...",18.247865,"{""suspect"": [""2 case(s) of \""missing previous ...",NaN,NaN,NaN,NaN

^ many NaNs

In [11]:
df.shape

(54, 66)

In [12]:
df.columns.tolist()

['timestep',
 'name',
 'longitude',
 'latitude',
 'accumulated_precipitation_1_minute_total',
 'accumulated_precipitation_1_minute_total_qc',
 'air_pressure_near_surface_1_minute_mean',
 'air_pressure_near_surface_1_minute_mean_qc',
 'air_pressure_near_surface_mean_sea_level_1_minute_mean',
 'air_pressure_near_surface_mean_sea_level_1_minute_mean_qc',
 'air_temperature_near_surface_1_minute_mean',
 'air_temperature_near_surface_1_minute_mean_qc',
 'air_temperature_near_surface_secondary_1_minute_mean',
 'air_temperature_near_surface_secondary_1_minute_mean_qc',
 'air_temperature_near_surface_sensor2_1_minute_mean',
 'air_temperature_near_surface_sensor2_1_minute_mean_qc',
 'cloud_base_height_layer1_1_minute_30_minute_rolling_min',
 'cloud_base_height_layer1_1_minute_30_minute_rolling_min_qc',
 'cloud_base_height_layer2_1_minute_30_minute_rolling_min',
 'cloud_base_height_layer2_1_minute_30_minute_rolling_min_qc',
 'cloud_base_height_layer3_1_minute_30_minute_rolling_min',
 'cloud_base_height_layer3_1_minute_30_minute_rolling_min_qc',
 'cloud_cover_layer1_1_minute_30_minute_weighted_mean',
 'cloud_cover_layer1_1_minute_30_minute_weighted_mean_qc',
 'cloud_cover_layer2_1_minute_30_minute_weighted_mean',
 'cloud_cover_layer2_1_minute_30_minute_weighted_mean_qc',
 'cloud_cover_layer3_1_minute_30_minute_weighted_mean',
 'cloud_cover_layer3_1_minute_30_minute_weighted_mean_qc',
 'cloud_cover_total_1_minute_30_minute_weighted_mean',
 'cloud_cover_total_1_minute_30_minute_weighted_mean_qc',
 'dew_point_temperature_1_minute_mean',
 'dew_point_temperature_1_minute_mean_qc',
 'direct_solar_irradiance_1_minute_60_minute_total',
 'direct_solar_irradiance_1_minute_60_minute_total_qc',
 'direct_solar_irradiance_1_minute_binary',
 'direct_solar_irradiance_1_minute_binary_qc',
 'direct_solar_irradiance_1_minute_mean',
 'direct_solar_irradiance_1_minute_mean_qc',
 'direct_solar_irradiance_secondary_1_minute_mean',
 'direct_solar_irradiance_secondary_1_minute_mean_qc',
 'global_radiation_1_minute_mean',
 'global_radiation_1_minute_mean_qc',
 'land_surface_temperature_concrete_1_minute_mean',
 'land_surface_temperature_concrete_1_minute_mean_qc',
 'land_surface_temperature_grass_1_minute_mean',
 'land_surface_temperature_grass_1_minute_mean_qc',
 'meteorological_optical_range_horizontal_1_minute_mean',
 'meteorological_optical_range_horizontal_1_minute_mean_qc',
 'precipitation_intensity_1_minute_rolling_algorithm',
 'precipitation_intensity_1_minute_rolling_algorithm_qc',
 'present_weather_1_minute_10_minute_weighted_mean',
 'present_weather_1_minute_10_minute_weighted_mean_qc',
 'relative_humidity_near_surface_1_minute_mean',
 'relative_humidity_near_surface_1_minute_mean_qc',
 'snow_depth_1_minute_mean',
 'snow_depth_1_minute_mean_qc',
 'soil_temperature_100cm_1_minute_mean',
 'soil_temperature_100cm_1_minute_mean_qc',
 'soil_temperature_10cm_1_minute_mean',
 'soil_temperature_10cm_1_minute_mean_qc',
 'soil_temperature_30cm_1_minute_mean',
 'soil_temperature_30cm_1_minute_mean_qc',
 'wind_direction_near_surface_1_minute_mean',
 'wind_direction_near_surface_1_minute_mean_qc',
 'wind_speed_near_surface_1_minute_mean',
 'wind_speed_near_surface_1_minute_mean_qc']

##### interesting; the file schema contains both the measurements and the qc field (..._qc")

In [13]:
df.dtypes

timestep                                            str
name                                                str
longitude                                       float64
latitude                                        float64
accumulated_precipitation_1_minute_total        float64
                                                 ...
soil_temperature_30cm_1_minute_mean_qc              str
wind_direction_near_surface_1_minute_mean       float64
wind_direction_near_surface_1_minute_mean_qc    float64
wind_speed_near_surface_1_minute_mean           float64
wind_speed_near_surface_1_minute_mean_qc        float64
Length: 66, dtype: object

In [14]:
df[["timestep", "name", "longitude", "latitude", "global_radiation_1_minute_mean"]].head(10)

,timestep,name,longitude,latitude,global_radiation_1_minute_mean
0,2026-09-16T09:06:00Z,High Beach Automatic Weather Station,0.04,51.66,NaN
1,2026-09-16T09:07:00Z,High Beach Automatic Weather Station,0.04,51.66,NaN
2,2026-09-16T09:08:00Z,High Beach Automatic Weather Station,0.04,51.66,NaN
3,2026-09-16T09:09:00Z,High Beach Automatic Weather Station,0.04,51.66,NaN
4,2026-09-16T09:10:00Z,High Beach Automatic Weather Station,0.04,51.66,NaN
5,2026-09-16T09:11:00Z,High Beach Automatic Weather Station,0.04,51.66,NaN
6,2026-09-16T09:12:00Z,High Beach Automatic Weather Station,0.04,51.66,NaN
7,2026-09-16T09:13:00Z,High Beach Automatic Weather Station,0.04,51.66,NaN
8,2026-09-16T09:14:00Z,High Beach Automatic Weather Station,0.04,51.66,NaN
9,2026-09-16T09:15:00Z,High Beach Automatic Weather Station,0.04,51.66,NaN

Let's narrow the df to solar vars:

In [15]:
solar_cols = [
    "timestep",
    "name",
    "longitude",
    "latitude",
    "global_radiation_1_minute_mean",
    "global_radiation_1_minute_mean_qc",
    "direct_solar_irradiance_1_minute_mean",
    "direct_solar_irradiance_1_minute_mean_qc",
]

df[solar_cols].head(10)

,timestep,name,longitude,latitude,global_radiation_1_minute_mean,global_radiation_1_minute_mean_qc,direct_solar_irradiance_1_minute_mean,direct_solar_irradiance_1_minute_mean_qc
0,2026-09-16T09:06:00Z,High Beach Automatic Weather Station,0.04,51.66,NaN,NaN,NaN,NaN
1,2026-09-16T09:07:00Z,High Beach Automatic Weather Station,0.04,51.66,NaN,NaN,NaN,NaN
2,2026-09-16T09:08:00Z,High Beach Automatic Weather Station,0.04,51.66,NaN,NaN,NaN,NaN
3,2026-09-16T09:09:00Z,High Beach Automatic Weather Station,0.04,51.66,NaN,NaN,NaN,NaN
4,2026-09-16T09:10:00Z,High Beach Automatic Weather Station,0.04,51.66,NaN,NaN,NaN,NaN
5,2026-09-16T09:11:00Z,High Beach Automatic Weather Station,0.04,51.66,NaN,NaN,NaN,NaN
6,2026-09-16T09:12:00Z,High Beach Automatic Weather Station,0.04,51.66,NaN,NaN,NaN,NaN
7,2026-09-16T09:13:00Z,High Beach Automatic Weather Station,0.04,51.66,NaN,NaN,NaN,NaN
8,2026-09-16T09:14:00Z,High Beach Automatic Weather Station,0.04,51.66,NaN,NaN,NaN,NaN
9,2026-09-16T09:15:00Z,High Beach Automatic Weather Station,0.04,51.66,NaN,NaN,NaN,NaN

In [16]:
df["global_radiation_1_minute_mean"].notna().sum()

np.int64(0)

^ this station doesn't have the global radiation data

In [17]:
df.notna().sum().sort_values(ascending=False)

timestep                                                 54
soil_temperature_10cm_1_minute_mean                      54
name                                                     54
land_surface_temperature_concrete_1_minute_mean          54
land_surface_temperature_concrete_1_minute_mean_qc       54
                                                         ..
cloud_cover_total_1_minute_30_minute_weighted_mean_qc     0
dew_point_temperature_1_minute_mean                       0
dew_point_temperature_1_minute_mean_qc                    0
direct_solar_irradiance_1_minute_60_minute_total          0
wind_speed_near_surface_1_minute_mean_qc                  0
Length: 66, dtype: int64

Now let's try to answer the more general Q of what stations have this solar data (most recently at least)

In [18]:
first_key

'202609161059_202609160906_202609160959/high_beach_automatic_weather_station_4291e137-ae60-42a9-9258-182cf338f7b0.csv'

In [19]:
batch_prefix = first_key.split('/',1)[0]

In [20]:
batch_prefix

'202609161059_202609160906_202609160959'

In [21]:
# this removed the slash, so need to add it back:
batch_prefix = batch_prefix + '/'

In [22]:
batch_prefix

'202609161059_202609160906_202609160959/'

In [23]:
batch_response = s3.list_objects_v2(
    Bucket=BUCKET_NAME,
    Prefix=batch_prefix,
)

batch_keys = [
    item["Key"]
    for item in batch_response.get("Contents", [])
]

print(f"Found {len(batch_keys)} files")

Found 1 files

In [24]:
from io import BytesIO
import pandas as pd

results = []

for key in batch_keys:
    csv_response = s3.get_object(
        Bucket=BUCKET_NAME,
        Key=key,
    )

    raw_data = csv_response["Body"].read()

    station_df = pd.read_csv(
        BytesIO(raw_data),
        sep="|",
    )

    results.append({
        "name": station_df["name"].iloc[0],
        "latitude": station_df["latitude"].iloc[0],
        "longitude": station_df["longitude"].iloc[0],
        "global_radiation_count": station_df["global_radiation_1_minute_mean"].notna().sum(),
        "direct_irradiance_count": station_df["direct_solar_irradiance_1_minute_mean"].notna().sum(),
    })

In [25]:
availability = pd.DataFrame(results)

availability.head()

,name,latitude,longitude,global_radiation_count,direct_irradiance_count
0,High Beach Automatic Weather Station,51.66,0.04,0,0

In [26]:
solar_stations = availability[
    (availability["global_radiation_count"] > 0)
    | (availability["direct_irradiance_count"] > 0)
]

solar_stations

Empty DataFrame
Columns: [name, latitude, longitude, global_radiation_count, direct_irradiance_count]
Index: []

In [27]:
print(f"Total stations in batch: {len(availability)}")
print(f"Stations with solar data: {len(solar_stations)}")
print(f"Stations with global radiation: {(availability['global_radiation_count'] > 0).sum()}")
print(f"Stations with direct irradiance: {(availability['direct_irradiance_count'] > 0).sum()}")

Total stations in batch: 1
Stations with solar data: 0
Stations with global radiation: 0
Stations with direct irradiance: 0

Didn't need to do all this to figure this out, but: the hardcoded batch_prefix is too limiting; we're not getting all the stations. So let's be more systematic...

In [28]:
response = s3.list_objects_v2(
    Bucket=BUCKET_NAME,
    MaxKeys=1000,
)

keys = [
    item["Key"]
    for item in response.get("Contents", [])
]

print(f"Objects returned: {len(keys)}")
print(f"More objects available: {response['IsTruncated']}")

Objects returned: 1000
More objects available: True

In [29]:
# now let's see how many different prefixes those first 1000 objects have:
prefixes = [key.split("/")[0] for key in keys]

print(f"Unique prefixes: {len(set(prefixes))}") # set() useful beacuse it removes duplicates, so we can count unique prefixes

Unique prefixes: 134

In [30]:
from collections import Counter

prefix_counts = Counter(prefixes)

prefix_counts.most_common(20)

[('202609210059_202609202300_202609202359', 245),
 ('202609210159_202609210000_202609210059', 191),
 ('202609202359_202609202200_202609202259', 79),
 ('202609200859_202609200700_202609200759', 25),
 ('202609202059_202609201900_202609201959', 23),
 ('202609200359_202609200200_202609200259', 20),
 ('202609200959_202609200800_202609200859', 20),
 ('202609200459_202609200300_202609200359', 19),
 ('202609202259_202609202100_202609202159', 19),
 ('202609200259_202609200100_202609200159', 18),
 ('202609201959_202609201800_202609201859', 17),
 ('202609201059_202609200900_202609200959', 16),
 ('202609202159_202609202000_202609202059', 16),
 ('202609200659_202609200500_202609200559', 14),
 ('202609200059_202609192300_202609192359', 13),
 ('202609200559_202609200400_202609200459', 13),
 ('202609200759_202609200600_202609200659', 13),
 ('202609201859_202609201700_202609201759', 13),
 ('202609201459_202609201300_202609201359', 12),
 ('202609200159_202609200000_202609200059', 11)]

- prefixes look hourly
- each prefix contains only 11 files, so a prefix is likely not the hourly batch for every station. Instead, seems to be grouped accorind to when data were released after processing
- abandon idea of selecting a prefix. instead ask: across all station files available in the bucket, which statations have reported solar data?
- need pagination since S3 only returns 1000 objects per request. boto3 has a paginator

In [31]:
paginator = s3.get_paginator("list_objects_v2")

pages = paginator.paginate(
    Bucket=BUCKET_NAME
)
# ^ not stored in memory, but something python can iterate through, one S3 response page at a time

In [32]:
# now collect all the keys:
all_keys = []

for page in pages:
    for item in page.get("Contents", []):
        all_keys.append(item["Key"])

print(f"Total objects in bucket: {len(all_keys)}")

Total objects in bucket: 53405

In [33]:
filenames = [
    key.split("/")[-1]
    for key in all_keys
]

print(f"Total files: {len(filenames)}")
print(f"Unique filenames: {len(set(filenames))}")

Total files: 53405
Unique filenames: 53405

In [34]:
all_keys[:10]

['202609161059_202609160906_202609160959/high_beach_automatic_weather_station_4291e137-ae60-42a9-9258-182cf338f7b0.csv',
 '202609161159_202609161000_202609161059/high_beach_automatic_weather_station_c1ee576f-4222-4761-8675-95c2c7fc0080.csv',
 '202609161259_202609161100_202609161159/high_beach_automatic_weather_station_8b3ab5de-09f1-4d75-90b2-a951f059114e.csv',
 '202609161359_202609161200_202609161259/high_beach_automatic_weather_station_762c7486-0600-4095-aa6b-8ecd038f6d7d.csv',
 '202609161459_202609161300_202609161359/high_beach_automatic_weather_station_b5b40431-ff40-45cf-8b3f-5e4762898436.csv',
 '202609161559_202609161400_202609161459/high_beach_automatic_weather_station_b1fa2e0e-d3fd-4b3f-957a-3476284880b1.csv',
 '202609161659_202609161500_202609161559/high_beach_automatic_weather_station_9d388201-fa26-4321-9557-61484bd58b35.csv',
 '202609161759_202609161600_202609161659/high_beach_automatic_weather_station_952763c0-2285-4e02-9864-63bf4a53dce6.csv',
 '202609161859_202609161700_202609161759/high_beach_automatic_weather_station_5ce3710f-d029-469c-8af1-e67782e102ca.csv',
 '202609161959_202609161800_202609161859/high_beach_automatic_weather_station_b58ce650-7458-491d-9636-108a9c7e575c.csv']

In [35]:
all_keys[-10:]

['202609290959_202609290800_202609290859/wittering_automatic_weather_station_a2b74410-5fbf-4762-9d1f-1754ea3d9032.csv',
 '202609290959_202609290800_202609290859/woburn_automatic_weather_station_ac663020-cdf0-4b17-ae81-3d3b36465a1e.csv',
 '202609290959_202609290800_202609290859/writtle_automatic_weather_station_712b4fc2-7045-421f-950a-6fc554efe55d.csv',
 '202609290959_202609290800_202609290859/wych_cross_automatic_weather_station_d5bc3761-f928-4c8d-b0ec-1ac8bf127cdc.csv',
 '202609290959_202609290800_202609290859/yeovilton_automatic_weather_station_c74c3e86-76f6-4bee-93c8-f5127e8fed1c.csv',
 '202609290959_202609290828_202609290859/dundrennan_automatic_weather_station_ceefdc30-d148-44cc-a84a-d334a4bfe4d3.csv',
 '202609290959_202609290858_202609290858/cavendish_automatic_weather_station_5d4b5565-5bc1-48c5-9ae5-bfc8b7d6bed9.csv',
 '202609290959_202609290858_202609290858/normanby_hall_automatic_weather_station_1e6c4444-c4b6-4291-80d7-51a2221edb5d.csv',
 '202609290959_202609290858_202609290859/newport_salop_automatic_weather_station_c7287c2f-4f0d-42a4-9a7c-0ed5d80d795d.csv',
 'index.html']

^ i did this at 2:04pm on 2026/09/11 so the latest is at 11:59UTC same day, so basically 12noon UTC or 1pm BST time, so ~65mins latency there for most recent data? but that's the time of release, maybe not the time of data collected...

Now let's take a look at all files on 2026/09/10 (yesterday, given the day I'm writing), at 12noon UTC (note I'm in BST time which is UTC+1)

In [36]:
midday_keys = []

for key in all_keys:
    prefix = key.split("/")[0]
    parts = prefix.split("_")

    if len(parts) == 3:
        observation_start = parts[1]

        if observation_start.startswith("2026092312"):
            midday_keys.append(key)

print(f"Files matching target hour: {len(midday_keys)}")

Files matching target hour: 262

^ updated this to sept 23 when i redid it; ideally shouldn't be hardcoded but this is just for diagnostics anyway

In [37]:
midday_keys[:10]

['202609231359_202609231200_202609231259/aberdaron_automatic_weather_station_070756f8-b536-4778-a39d-3d1cee82a041.csv',
 '202609231359_202609231200_202609231259/abergwyngregyn_automatic_weather_station_637b523e-fa24-4b2a-9c6d-34c4134a479e.csv',
 '202609231359_202609231200_202609231259/aberporth_automatic_weather_station_2a95065c-033d-4360-8c42-0def42ad981e.csv',
 '202609231359_202609231200_202609231259/aboyne_no_2_automatic_weather_station_a6b73120-8f0f-4546-9059-44dbf322f360.csv',
 '202609231359_202609231200_202609231259/achnagart_automatic_weather_station_f78f57e0-ef1b-4e8b-9182-3bd52fa1d5b7.csv',
 '202609231359_202609231200_202609231259/akrotiri_cyprus_automatic_weather_station_a364f3df-4820-49c9-a097-e63ab13d6e62.csv',
 '202609231359_202609231200_202609231259/albemarle_automatic_weather_station_94dcb26a-078e-4ba7-a7f7-d6554223a4f4.csv',
 '202609231359_202609231200_202609231259/aldergrove_automatic_weather_station_c443bbf3-b8f4-4908-9bae-4b68ab52537a.csv',
 '202609231359_202609231200_202609231259/alice_holt_lodge_automatic_weather_station_0bd5f206-98c0-413b-8eb1-8e21656fe697.csv',
 '202609231359_202609231200_202609231259/almondsbury_automatic_weather_station_aeedc5a0-e29c-4625-adca-428439449778.csv']

In [38]:
solar_results = []

for key in midday_keys:
    csv_response = s3.get_object(
        Bucket=BUCKET_NAME,
        Key=key,
    )

    raw_data = csv_response["Body"].read()

    station_df = pd.read_csv(
        BytesIO(raw_data),
        sep="|",
    )

    global_count = station_df["global_radiation_1_minute_mean"].notna().sum()
    direct_count = station_df["direct_solar_irradiance_1_minute_mean"].notna().sum()

    solar_results.append({
        "name": station_df["name"].iloc[0],
        "latitude": station_df["latitude"].iloc[0],
        "longitude": station_df["longitude"].iloc[0],
        "global_count": global_count,
        "direct_count": direct_count,
    })

solar_availability = pd.DataFrame(solar_results)

In [39]:
len(solar_availability) # how many stations have data at this hour? (it only needs to have one row of data to be included in the list, even if it has no solar data, i think)

262

In [40]:
(solar_availability["global_count"] > 0).sum() # how many stations have global radiation data at this hour?

np.int64(87)

In [41]:
(solar_availability["direct_count"] > 0).sum()

np.int64(100)

^ answers: 83 have GHI, 94 have DNI. That's not too bad! probably more then the number of solarsense nodes I'd realistically deploy in my dphil...

edit on 24 sept: now i'm getting 87 GHI, 100 DNI. So it seems to vary quite a bit day by day.

In [42]:
#which ones?
solar_stations = solar_availability[
    (solar_availability["global_count"] > 0)
    | (solar_availability["direct_count"] > 0)
].copy()

solar_stations.sort_values("name")

,name,latitude,longitude,global_count,direct_count
0,Aberdaron Automatic Weather Station,52.79,-4.74,60,60
1,Abergwyngregyn Automatic Weather Station,53.24,-4.01,60,60
2,Aberporth Automatic Weather Station,52.14,-4.57,60,60
5,"Akrotiri, Cyprus Automatic Weather Station",34.58,32.98,0,60
7,Aldergrove Automatic Weather Station,54.66,-6.23,60,60
...,...,...,...,...,...
251,Winterbourne No 2 Automatic Weather Station,52.46,-1.93,60,60
252,Wisley Automatic Weather Station,51.31,-0.48,60,60
253,Wittering Automatic Weather Station,52.61,-0.47,60,60
254,Woburn Automatic Weather Station,52.01,-0.60,60,60
257,Yeovilton Automatic Weather Station,51.01,-2.64,60,60

In [43]:
solar_stations

,name,latitude,longitude,global_count,direct_count
0,Aberdaron Automatic Weather Station,52.79,-4.74,60,60
1,Abergwyngregyn Automatic Weather Station,53.24,-4.01,60,60
2,Aberporth Automatic Weather Station,52.14,-4.57,60,60
5,"Akrotiri, Cyprus Automatic Weather Station",34.58,32.98,0,60
7,Aldergrove Automatic Weather Station,54.66,-6.23,60,60
...,...,...,...,...,...
251,Winterbourne No 2 Automatic Weather Station,52.46,-1.93,60,60
252,Wisley Automatic Weather Station,51.31,-0.48,60,60
253,Wittering Automatic Weather Station,52.61,-0.47,60,60
254,Woburn Automatic Weather Station,52.01,-0.60,60,60
257,Yeovilton Automatic Weather Station,51.01,-2.64,60,60

In [44]:
2

2

In [45]:
import folium

m = folium.Map(
    location=[54.5, -3],
    zoom_start=5,
)

for _, station in solar_stations.iterrows():
    folium.Marker(
        location=[station["latitude"], station["longitude"]],
        tooltip=station["name"],
    ).add_to(m)

# could have used 'for i,j in solar_stations' but since we don't use i in the loop, the underscore is the convention. 
# but if you open up solar_stations, you'll see that there is an initial column seemingly with no title, and then the second
# column title is 'name', so I guess that's why we need a dummy variable there. The underscore is not special python syntax;
# it's just a normal variable name, used by convention to show that a value will not be used!

# m

In [46]:
solar_stations

,name,latitude,longitude,global_count,direct_count
0,Aberdaron Automatic Weather Station,52.79,-4.74,60,60
1,Abergwyngregyn Automatic Weather Station,53.24,-4.01,60,60
2,Aberporth Automatic Weather Station,52.14,-4.57,60,60
5,"Akrotiri, Cyprus Automatic Weather Station",34.58,32.98,0,60
7,Aldergrove Automatic Weather Station,54.66,-6.23,60,60
...,...,...,...,...,...
251,Winterbourne No 2 Automatic Weather Station,52.46,-1.93,60,60
252,Wisley Automatic Weather Station,51.31,-0.48,60,60
253,Wittering Automatic Weather Station,52.61,-0.47,60,60
254,Woburn Automatic Weather Station,52.01,-0.60,60,60
257,Yeovilton Automatic Weather Station,51.01,-2.64,60,60

In [47]:
m.save("../data/solar_stations_map.html")

In [48]:
import folium

m = folium.Map(
    location=[54.5, -3],
    zoom_start=5,
)

for _, station in solar_availability.iterrows():

    # Global horizontal irradiance (GHI)
    if station["global_count"] > 0:
        folium.CircleMarker(
            location=[station["latitude"], station["longitude"]],
            radius=6,
            color="blue",
            fill=True,
            fill_color="blue",
            fill_opacity=0.7,
            tooltip=f"{station['name']} — GHI",
        ).add_to(m)

    # Direct irradiance
    if station["direct_count"] > 0:
        folium.CircleMarker(
            location=[station["latitude"], station["longitude"]],
            radius=3,
            color="red",
            fill=True,
            fill_color="red",
            fill_opacity=0.9,
            tooltip=f"{station['name']} — Direct",
        ).add_to(m)

# m

In [49]:
m.save("../data/solar_stations_map.html")

Wow, there is one in gibraltar and one in cyrpus as well!
- also jersey, IoM, NI, and very northern scotland, but those are to be expected I guess